config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    resources :books
    root to: 'static_pages#home'
    get 'books/:id/confirm_delete', to: 'books#confirm_delete', as: 'confirm_delete_book'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    
 #index view should produce a list of books
        def index
          @books = Book.order(title: :asc)

      end

        def create
        book_params = params.require(:book).permit(:title, :author, :rating)
        @book = Book.new(book_params)

            if @book.save
              redirect_to @book, notice: 'Book was successfully created.'
              return
            else
              render :new
            end
      end


       def new
          @book = Book.new
      end

         def edit
            @book = Book.find params[:id]
          end



      def show
         @book = Book.find params[:id] 
      end

       def update
        @book = Book.find params[:id]
        book_params = params.require(:book).permit(:title, :author, :rating)
            if @book.update(book_params)
              redirect_to @book, notice: 'Book was successfully updated.'
              return
            else
              render :edit
            end
      end

        def destroy
        @book = Book.find params[:id]
        @book.destroy
        redirect_to books_url, notice: 'Book was successfully destroyed.'
      end

    
        def confirm_delete
          @book = Book.find params[:id] 
        end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/books/confirm_delete.erb
  
<h1>Delete Books</h1>

<p>Do you really want to delete <%= @book.title %>?</p>


    <td><%= form_with model: @book, local: true, method: 'delete' do |f| %>
                 <%= f.submit "Delete" %>     
             <% end %></td>
    
     
    <td><%= link_to "Cancel delete", book_path %></td>

app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/books/destroy.html.erb
<h1>Books#destroy</h1>
<p>Find me in app/views/books/destroy.html.erb</p>

app/views/books/edit.html.erb
<h1>Edit an existing Book</h1>

<%= form_with(model: @book, local: true) do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div>
    <%= form.label :rating %>
    <%= form.number_field :rating %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/books/index.html.erb
<h1>Books</h1>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>author</th>
      <th>rating</th>
      <th colspan=3></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      
      <tr>
           <td><%= link_to book.title, book_path(book) %></td>
          
           <td><%= book.author %></td>
           <td><%= book.rating %></td>
         
         
      </tr>
      
    <% end %>
      
      
    
         
  </tbody>
    
</table>

      <p><td><%= link_to "Home", root_path %></td></p>
      <p><td><%= link_to "Add a Book", new_book_path %></td></p>

app/views/books/new.html.erb
<h1>Add a Book to the DB</h1>

<%= form_with(model: @book, local: true) do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div>
    <%= form.label :rating %>
    <%= form.number_field :rating %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/books/show.html.erb
<h1>Book with id = <%= @book.id %></h1>
<table>
    <tr><td>Title:</td><td><%= @book.title %></td></tr>
    <tr><td>Author:</td><td><%= @book.author %></td></tr>
    <tr><td>Rating:</td><td><%= @book.rating %></td></tr>
    
      <tbody>
    
   
       
  </tbody>
    
    
</table>

   <p><td><%= link_to "Home", root_path %></td></p>
   <p><td><%= link_to "List of books", books_path %></td></p>
   <p><td><%= link_to "Edit this book", edit_book_path %></td></p>
   <p><td><%= link_to "Delete Book", confirm_delete_book_path %></td></p>

app/views/books/update.html.erb
<h1>Books#update</h1>
<p>Find me in app/views/books/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dana Lee's BasicBooks App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>

   <body>
   <%# Modified from: https://stackoverflow.com/questions/9390778/best-practice-method-of-displaying-flash-messages %>
   
   <% flash.each do |key, value| %>
     <%= content_tag :div, value, id: "#{key}" %>
   <% end %>      
     
   <%= yield %>
 </body>
</html>

app/views/static_pages/home.html.erb
<h1>BasicBooks</h1>

<table>
  <thead>
                
      <td><%= link_to "Dana Lee's BookList", books_path %></td>
         
      
  </thead>
  
</table>